/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Data.ComidaData;
import Data.DietaComidaData;
import Data.DietaData;
import Data.PacienteData;
import Entidades.Comida;
import Entidades.Dieta;
import Entidades.DietaComida;
import Entidades.Paciente;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.EditorKit;

/**
 *
 * @author Loboplateado77
 */
public class TipoDieta extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {
            //si pongo false entonces las celdas no son editables
            return false;
        }
    };

    /**
     * Creates new form Comida
     */
    public TipoDieta() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //import javax.swing.ImageIcon;
        ImageIcon icono  = new  ImageIcon(getClass().getResource("/Recursos/empanadas.png"));
        Image miImagenjpg = icono.getImage();
        jPanel7 = new javax.swing.JPanel(){public void paintComponent(Graphics g){
            g.drawImage(miImagenjpg,0,0,getWidth(),getHeight(),this);
        }
    }
    ;
    jBagregar = new javax.swing.JButton();
    jBsalir = new javax.swing.JButton();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
    jScrollPane1 = new javax.swing.JScrollPane();
    jTdieta = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jLIdDieta = new javax.swing.JLabel();
    jTIdDieta = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jTDni = new javax.swing.JTextField();
    jBBuscar = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jTNombre = new javax.swing.JTextField();
    jTDieta = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setClosable(true);

    jPanel7.setForeground(new java.awt.Color(153, 153, 153));

    jBagregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jBagregar.setText("Agregar");
    jBagregar.setEnabled(false);
    jBagregar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBagregarActionPerformed(evt);
        }
    });

    jBsalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jBsalir.setText("Salir");
    jBsalir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBsalirActionPerformed(evt);
        }
    });

    jTdieta.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "ID Comida", "Nombre", "Detalle", "Cant. Calorías"
        }
    ));
    jScrollPane1.setViewportView(jTdieta);

    jPanel1.setBackground(new java.awt.Color(255, 255, 204));

    jLIdDieta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLIdDieta.setText("Codigo Dieta");

    jTIdDieta.setEditable(false);

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLabel3.setText("DNI");

    jTDni.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTDniKeyReleased(evt);
        }
    });

    jBBuscar.setText("Buscar");
    jBBuscar.setEnabled(false);
    jBBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBBuscarActionPerformed(evt);
        }
    });

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLabel4.setText("Nombre");

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLabel5.setText("Dieta");

    jTNombre.setEditable(false);

    jTDieta.setEditable(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLIdDieta)
                    .addGap(18, 18, 18)
                    .addComponent(jTIdDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTDieta)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(99, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLIdDieta)
                .addComponent(jTIdDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBBuscar))
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(36, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(204, 255, 153));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setText("CREAR PLAN NUTRICIONAL");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(254, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(212, 212, 212))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(19, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(91, 91, 91)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addComponent(jBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40))
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(35, 35, 35)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(41, 41, 41)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBagregar)
                .addComponent(jBsalir))
            .addGap(34, 34, 34))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // salir
        setVisible(false);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jTDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDniKeyReleased
        try {
            if (!jTDni.getText().isEmpty()) {
                int dni = Integer.parseInt(jTDni.getText());
                PacienteData pacData = new PacienteData();
                if (pacData.buscarPacientexDNI(dni) != null) {
                    Paciente paciente = pacData.buscarPacientexDNI(dni);
                    DietaData dietaData = new DietaData();
                   // DietaComidaData dieComiData = new DietaComidaData();
                    int idPac = paciente.getIdPaciente();
                    if (dietaData.buscarDietaPorPaciente(idPac) != null) {
                        jBagregar.setEnabled(true);
                        jBBuscar.setEnabled(true);
                        Dieta dieta = dietaData.buscarDietaPorPaciente(idPac);
                        int idDieta = dieta.getIdDieta();
                        jTIdDieta.setText(idDieta + "");
                        jTNombre.setText(paciente.getNombre());
                        jTDieta.setText(dieta.getNombre());
                    } else {
                        borrarCampos();
                        borrarFila();
                    }
                } else {
                    borrarCampos();
                    jBagregar.setEnabled(false);
                    borrarFila();
                }
            } else {
                borrarCampos();
                jBagregar.setEnabled(false);
                borrarFila();
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Ingrese caracteres numéricos");
            jTDni.setText("");
        }
    }//GEN-LAST:event_jTDniKeyReleased

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if (!jTDni.getText().isEmpty()) {
            cargarTabla();
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
     
        try {   
            DietaComidaData dieCoData = new DietaComidaData();
            ComidaData  comidaData = new ComidaData();
            DietaData dietaData = new DietaData();
            int idDieta =Integer.parseInt(jTIdDieta.getText());
            Dieta dieta = dietaData.buscarDietaxId(idDieta);
            
            int fila = jTdieta.getSelectedRow();
            if (fila != -1) {
                int iDcomida = (int) modelo.getValueAt(fila, 0);
                Comida comi = comidaData.buscarComidaxId(iDcomida);
                DietaComida dietaCo = new DietaComida(comi, dieta);
                dieCoData.altaDieta(dietaCo);
            if (!jTDni.getText().isEmpty()) {
                cargarTabla();
            }
            }
        } catch (NumberFormatException nf ){
            JOptionPane.showMessageDialog(this, "Debe ingresar sólo caracteres numéricos");
        }
    }//GEN-LAST:event_jBagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLIdDieta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDieta;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTIdDieta;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTable jTdieta;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("idComida");
        modelo.addColumn("Nombre");
        modelo.addColumn("Detalle");
        modelo.addColumn("Cant. Calorias");
        jTdieta.setModel(modelo);
    }

    private void borrarFila() {
        int f = jTdieta.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

    private void cargarTabla() {
        borrarFila();
        int idDieta = Integer.parseInt(jTIdDieta.getText());
       // DietaData dietaData = new DietaData();
        DietaComidaData dietaComiData = new DietaComidaData();
        //Dieta dieta = dietaData.buscarDietaxId(idDieta);
        ComidaData comiData = new ComidaData();
        TreeSet<Integer> tabla = new TreeSet();
        
            for (Comida comidacha :comiData.listarTodasComidas()) {
                tabla.add(comidacha.getIdComida());  
            }
            
            for (Comida comidacha :dietaComiData.listarComidasPorDieta(idDieta)) {
                tabla.remove(comidacha.getIdComida());
            }
            
        for (Integer id : tabla) {
            Comida com = comiData.buscarComidaxId(id);
          modelo.addRow(new Object[]{com.getIdComida(), com.getNombre(), com.getDetalle(), com.getCantCalorias()});
        }
    }
    private void borrarCampos(){
        jBBuscar.setEnabled(false);
        jTIdDieta.setText("");
        jTNombre.setText("");
        jTDieta.setText("");
    }
}
